### ISSUE TITLE
FakeItEasy support

### ISSUE THREAD

**Issue by vchirikov** [MrLuje/Mocking.Helpers#5]
Hi
Do you planning add FakeItEasy support?

**Comment by MrLuje** [comment]
Never used that one, but why not :)

The syntax is : 
`A.CallTo(() => foo.Bar(A<string>.Ignored, A<int>.Ignored))`

Correct ?

**Comment by vchirikov** [comment]
Yep, I think `A<string>._` is better.  
[docs](https://fakeiteasy.readthedocs.io/en/stable/argument-constraints/#ignoring-arguments)

**Comment by vchirikov** [comment]
@MrLuje best! Don't forget update marketplace vsix and description.
p.s. in repo description link to marketplace is broken.
